# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - functions
#   - deploy
#   - get_dealer_applicant_analysis_report
#   - --source=.
#   - --trigger-http
#   - --runtime=python37
#   - --timeout=90
#   - --memory=2GB
#   - --vpc-connector=mongo-connector
#   - --egress-settings=all


steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - get_dealer_applicant_analysis_report
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --timeout=90
  - --memory=2GB
  #- --vpc-connector=wfd-serverlessvpc-99
  - --vpc-connector=mongo-connector
  - --egress-settings=all
  - --service-account=fninvoker@webfinancedirect-dev.iam.gserviceaccount.com
  # - --set-secrets=/etc/secrets/primary/latest=fninvoker-key:latest
  # - --set-env-vars=REPORT_BUCKET=wfd-reporting-bkt-99-prd,REP_REPORT_DIR=lender-reports
  - --set-secrets=/etc/secrets/primary/latest=fninvoker-key-dev:latest
  - --set-env-vars=REPORT_BUCKET=wfd-reporting-01,REP_REPORT_DIR=lender-reports