#!/bin/zsh
zip fm_commission_report.zip main.py requirements.txt
gcloud builds submit --config cloudbuild.yaml fm_commission_report.zip
#gcloud functions deploy get_fm_commission_report --vpc-connector mongo-connector --egress-settings=all
